name: FM 108 WDMT
favicon: null
layout_spectrum: 0.24446092126891017
typography_spectrum: 0.8871220278088003
title: FM 108 WDMT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b090a'
    - '#65bb22'
    - '#fbfbfb'
    - '#3a6222'
    - '#a3a1a6'
  brandStrength: 0.32928755204193294
  lightness: 0.2660946005489677
  saturation: 0.2221602932550013
  rhythmicContrast: 0.47066109254956245
purpose: []
